id: ACD2FEDB3
base_file: f027C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:55:32.565445
  last_modified_at: 2022-05-30 21:55:32.565451
